# Generated by Django 5.2.3 on 2025-07-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test_slug', unique=True),
            preserve_default=False,
        ),
    ]
